version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: project-postgres
    environment:
      POSTGRES_DB: project_analytics
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics123
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - analytics-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U analytics_user -d project_analytics -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: project-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    networks:
      - analytics-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  analytics-network: